# Generated by Django 5.0.4 on 2024-04-06 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_book_cover'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='OrderItem',
        ),
    ]
