# Generated by Django 5.0.4 on 2024-04-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_book_table_alter_order_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderBook',
        ),
        migrations.AddField(
            model_name='book',
            name='product_type',
            field=models.CharField(default='book', max_length=100),
        ),
    ]
