# Generated by Django 5.0.4 on 2024-04-08 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_rename_orderitem_orderbook_book_product_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderbook',
            table='OrderBook',
        ),
    ]
