# Generated by Django 5.0.4 on 2024-04-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_rename_id_book_book_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
