# Generated by Django 5.0.4 on 2024-04-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_alter_order_total'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='PurchaseOrder',
        ),
        migrations.AlterModelTable(
            name='orderbook',
            table='OrderDetail',
        ),
    ]
