# Generated by Django 5.0.4 on 2024-04-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_alter_order_table_alter_orderbook_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderBook',
            new_name='OrderDetail',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='PurchaseOrder',
        ),
    ]
