# Generated by Django 5.0.4 on 2024-05-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_game_remove_orderdetail_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=200)),
                ('operating_systems', models.CharField(max_length=100)),
                ('date_released', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('about_game', models.TextField()),
                ('gameplay', models.TextField()),
                ('price', models.FloatField()),
                ('video', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
