# Generated by Django 4.2 on 2024-05-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_gamedetail_gameinfo_delete_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
