# Generated by Django 4.2 on 2024-05-12 09:36

from django.db import migrations
import playground.models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_alter_gamedetail_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='date_released',
            field=playground.models.CustomDateField(),
        ),
    ]
