# Generated by Django 4.2 on 2024-05-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0015_alter_gameinfo_gameplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
